### ISSUE TITLE
Problem with already Installed higher Framework Bundle4.1.11

### ISSUE THREAD

**Issue by mr2017x** [heimrichhannot/contao-youtube-bundle#3]
Hi Guys,

thanks for your contao add-in, when try to install i faced sadly the following problem (guess because an already installed other plugin)

```
Problem 1
    - Installation request for heimrichhannot/contao-youtube-bundle ^3.2 -> satisfiable by heimrichhannot/contao-youtube-bundle[3.2.0].
    - Conclusion: remove symfony/framework-bundle v4.1.11
    - Conclusion: don't install symfony/framework-bundle v4.1.11
    - heimrichhannot/contao-youtube-bundle 3.2.0 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/framework-bundle[v3.4.0, v4.1.11].
```

(Contao 4.6.14)

Can you tell me, how to go around this? 

Thank you in advance and have a sunny sunday :-)

**Comment by fatcrobat** [comment]
Should be fixed in 3.2.1.

**Comment by mr2017x** [comment]
Hi,

thank you, it went further, but:


```
In DefinitionErrorExceptionPass.php line 54:
                                                                               
  Cannot autowire service "huh.youtube.videocreator": argument "$request" of   
  method "HeimrichHannot\YoutubeBundle\Video\VideoFactory::__construct()" ref  
  erences class "HeimrichHannot\RequestBundle\Component\HttpFoundation\Reques  
  t" but no such service exists. You should maybe alias this class to the exi  
  sting "huh.request" service.                                                 
                                                                               

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

In ScriptHandler.php line 87:
                                                                               
  An error occurred while executing the "contao:install-web-dir" command:      
  In DefinitionErrorExceptionPass.php line 54:                                 
                                                                               
                                                                               
    Cannot autowire service "huh.youtube.videocreator": argument "$request" o  
  f                                                                            
    method "HeimrichHannot\YoutubeBundle\Video\VideoFactory::__construct()" r  
  ef                                                                           
    erences class "HeimrichHannot\RequestBundle\Component\HttpFoundation\Requ  
  es                                                                           
    t" but no such service exists. You should maybe alias this class to the e  
  xi                                                                           
    sting "huh.request" service.         

```

**Comment by fatcrobat** [comment]
Alright, seems `heimrichhannot/contao-request-bundle` related. Created version `1.0.7` in order to create class alias for `@huh.request` in symfony 4.x. Can you please run `composer update`  and try again with `heimrichhannot/contao-request-bundle` version `1.0.7`?

**Comment by mr2017x** [comment]
Hi fatcrobat, 

thank you very much for your help. i run composer update, but the problem is still the same - furthermore it breaks contao (happily autorecovery works properly). Can you tell me, where i can view the version (1.0.7?)

Thanks

**Comment by fatcrobat** [comment]
Run „composer show -l“ on command line
